name: CI - Hardhat Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Hardhat tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (LTS version)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Compile contracts
      - name: Compile contracts
        run: npx hardhat compile

      # Step 5: Run tests
      - name: Run test suite
        run: npx hardhat test

      # (Optional) Step 6: Show gas usage report (if you use hardhat-gas-reporter)
      - name: Gas report (optional)
        if: always()
        run: |
          echo "Generating gas usage report..."
          npx hardhat test --report-gas || echo "Gas report skipped"
